### ISSUE TITLE
Traing file 

### ISSUE THREAD

**Issue by premkarki47** [Deevoluation/ALPR#4]
can you email me a training file and making .h5 file email: pr3mcark3y@gmail.com

**Comment by premkarki47** [comment]
i get following errors while running this file
Using TensorFlow backend.
Found 5043 images belonging to 1 classes.
Found 480 images belonging to 1 classes.
Epoch 1/5
Traceback (most recent call last):
  File "E:/Main Program/train_detect.py", line 59, in <module>
    classifier.fit_generator(train_set,steps_per_epoch=47605,epochs=5,validation_data=test_set,validation_steps=1292,callbacks=[csv])
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 787, in _standardize_user_data
    exception_prefix='target')
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training_utils.py", line 137, in standardize_input_data
    str(data_shape))

**Comment by premkarki47** [comment]
i have change that live but still i have the following errors

Using TensorFlow backend.
Found 5043 images belonging to 1 classes.
Found 480 images belonging to 1 classes.
Epoch 1/5
Traceback (most recent call last):
  File "E:/Main Program/train_detect.py", line 59, in <module>
    classifier.fit_generator(train_set,steps_per_epoch=5043,epochs=5,validation_data=test_set,validation_steps=480,callbacks=[csv])
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training.py", line 787, in _standardize_user_data
    exception_prefix='target')
  File "F:\College\final year project\python ANPR\python ANPR\ANPR\venv\lib\site-packages\keras\engine\training_utils.py", line 137, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_2 to have shape (36,) but got array with shape (1,)

**Comment by premkarki47** [comment]
what is the meaning of temp.jpg

import cv2 
import numpy as np
img=cv2.imread('temp1.jpg')
img=cv2.resize(img,(64,64))
img=np.reshape(img,[1,64,64,3])
classes=classifier.predict_classes(img)
print(classes)

**Comment by premkarki47** [comment]
thank you for solving this problems!! I appreciate your support.
