### ISSUE TITLE
Error While executing the Main.py

### ISSUE THREAD

**Issue by hbsuhas** [Deevoluation/ALPR#7]
C:\Alpr\ALPR\Main Program>Main.py
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Alpr\ALPR\Main Program\Main.py", line 8, in <module>
    import DetectChars
  File "C:\Alpr\ALPR\Main Program\DetectChars.py", line 49, in <module>
    model = load_model('New_model/char-reg.h5')
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 418, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 224, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 457, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 294, in from_config
    model = cls(name=name)
**UnboundLocalError: local variable 'name' referenced before assignment**

**Comment by Saqhas** [comment]
This problem seems to be with the installed Keras or with the repo is cloned incorrectly.
I would recommend to uninstall tensorflow, keras and install them from scratch. Then freshly clone the repo  .
If the same problem still persists, Please inform here.
If some other error comes, feel free to post it here.

**Comment by hbsuhas** [comment]
Hello,

Thank you for response.

I have uninstalled keras 2.2x and installed lower version of keras then it
worked.

Thank you
Suhas Hb

**Comment by Siddhant96** [comment]
Hi,

Glad to hear that your problem is resolved. Feel free to contact us for any
future assistance.
Please star mark the repository if you liked it.

Thank You,
Siddhant Khandelwal
